server:
  port: 8085

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/payments?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:zyz}
    password: ${SPRING_DATASOURCE_PASSWORD:zyz703}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

topics:
  payment-processed: ${TOPIC_PAYMENT_PROCESSED:payments.payment.processed}
  payment-reversed:  ${TOPIC_PAYMENT_REVERSED:payments.payment.reversed}

jwt:
  secret: ${JWT_SECRET}
